### ISSUE TITLE
Windows release versions are not working

### ISSUE THREAD

**Issue by hadoooooouken** [WolvenKit/wwise-audio-tools#13]
Hi, I got errors about missing VCRUNTIME140D.dll and some other libs. It seems like you build Debug version in MSVC instead Release. So it would works only if user has installed MSVC.

**Comment by ADawesomeguy** [comment]
It gets auto released by GitHub's CI and is built with CMake, so I may be able to fix this pretty easily.

**Comment by ADawesomeguy** [comment]
@hadoooooouken could you please try the latest release (0.8.1)? It should fix the problem.

**Comment by hadoooooouken** [comment]
Now it converts without errors, thx! But still can't play resulted ogg at my system. But this problem also persist with ww2ogg and revorb.<br>
ffplay test.ogg give me:
```
F:\ww_test>ffplay test.ogg
ffplay version N-109078-g2d25f33a7e-20221113 Copyright (c) 2003-2022 the FFmpeg developers
  built with gcc 12.2.0 (crosstool-NG 1.25.0.90_cf9beb1)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --disable-libmfx --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20221113
  libavutil      57. 42.100 / 57. 42.100
  libavcodec     59. 52.102 / 59. 52.102
  libavformat    59. 34.101 / 59. 34.101
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 50.100 /  8. 50.100
  libswscale      6.  8.112 /  6.  8.112
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    56.  7.100 / 56.  7.100
[ogg @ 000002ab6505be40] CRC mismatch! vq=    0KB sq=    0B f=0/0
    Last message repeated 41 times
[ogg @ 000002ab6505be40] CRC mismatch! vq=    0KB sq=    0B f=0/0
    Last message repeated 56 times
[ogg @ 000002ab6505be40] CRC mismatch! vq=    0KB sq=    0B f=0/0
    Last message repeated 42 times
[ogg @ 000002ab6505be40] CRC mismatch! vq=    0KB sq=    0B f=0/0
    Last message repeated 57 times
[ogg @ 000002ab6505be40] CRC mismatch! vq=    0KB sq=    0B f=0/0
    Last message repeated 42 times
[ogg @ 000002ab6505be40] CRC mismatch! vq=    0KB sq=    0B f=0/0
    Last message repeated 57 times
[ogg @ 000002ab6505be40] CRC mismatch! vq=    0KB sq=    0B f=0/0
    Last message repeated 57 times
[ogg @ 000002ab6505be40] CRC mismatch! vq=    0KB sq=    0B f=0/0
    Last message repeated 42 times
[ogg @ 000002ab6505be40] CRC mismatch! vq=    0KB sq=    0B f=0/0
    Last message repeated 53 times
test.ogg: End of file
    nan    :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0
```
This file was getting from CP2077 through Wolwenkit

**Comment by ADawesomeguy** [comment]
Unfortunately this issue will take more time and effort to solve since OGG conversion is just a wrapper around `ww2ogg` and `revorb` at the moment. Would you mind creating another issue with this info as it is no longer relevant to the topic of this issue? Thanks!
